name: "Build fap App"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    name: 'ufbt: Build for release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
